config/routes.rb
Weddify::Application.routes.draw do

  resources :users
  resources :stories 
  resources :sessions, only: [:new, :create, :destroy]
  resources :items
  resources :photos

  resources :galleries
  resources :providers

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/blog', to: 'static_pages#blog'
  
  match '/signout', to: 'sessions#destroy'
  match '/signin', to: 'sessions#new'
  
   match ":name_groom.:name_bride.:last_name", to: 'users#show'
    match ":name", to: 'providers#show'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
	attr_accessible :category, :email, :name, :password_digest, :password, :password_confirmation, :avatar
	has_attached_file :avatar, dependent: :destroy

	def check_content_type
		if !['image/jpeg', 'image/gif','image/png'].include?(self.avatar_content_type)
			errors[:base] << ("Slika '#{self.avatar_file_name}' nema validnu ekstenziju, koristite img, gif ili png")
		end
	end 

	has_secure_password

	before_save { |user| user.email = email.downcase}
	before_save :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	validates :category, presence: true, :inclusion => 1...5

	has_one :story, dependent: :destroy
	has_one :gallery, dependent: :destroy

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
	before_filter :signed_in_user, only: [:edit, :update]
	#before_filter :correct_user, only: [:edit, :update]
	#before_filter :admin_user, only: :destroy

	def new
		@provider=Provider.new
		

	end

	def show
		@provider=Provider.where("lower(name) =?" ,params[:name]).first
		if @provider == nil
			@provider = Provider.find_by_id(params[:id])
		end

		if !@provider || @provider == nil
			redirect_to root_path
			return
		end

		@story = Story.find_by_provider_id(@user.id)
		@items=Item.find_all_by_provider_id(@user.id)
		@photos = @provider.gallery.photos
	end

	def create
		@provider = Provider.new(params[:provider])
		if @provider.save
			story = Story.new
			story.user_id = @provider.id
			story.story_text = t('tell_your_story')
			@provider.story = story
			@provider.story.save
			@provider.gallery=Gallery.new
			sign_in @provider
			flash[:green] = t('created_profile')
			redirect_to @provider
		else
			render 'new'
		end
	end

	private
	def correct_user
		@provider = Provider.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end


end

app/helpers/providers_helper.rb
module ProvidersHelper

	def category_to_string(number)
		case number
		when 1
			return t('place')
		when 2
			return t('food')
		when 3
			return t('flowers')
		when 4
			return t('jewelry')
		end
	end
end

app/views/providers/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for @provider, :url => providers_path, :html => { :multipart => true } do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>
		<%= f.label :category %>
		<%= f.select(:category, options_for_select( [ [category_to_string(1), 1] , [category_to_string(2), 2], [category_to_string(3), 3], [category_to_string(4), 4]  ]  )) %>
		<%= f.file_field :avatar %>
	</br>
		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>