config/routes.rb
Weddify::Application.routes.draw do

  resources :users
  resources :stories 
  resources :sessions, only: [:new, :create, :destroy]
  resources :items
  resources :photos

  resources :galleries
  resources :providers

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'users#new'
  match '/blog', to: 'static_pages#blog'
  
  match '/signout', to: 'sessions#destroy'
  match '/signin', to: 'sessions#new'
  
   match ":name_groom.:name_bride.:last_name", to: 'users#show'
    match ":name", to: 'providers#show'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		
	end

	def help
	end

	def about
	end

	def contact
	end

	def search
		
	end

	def blog
	end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'O Nama') %>
<h1>O Nama</h1>

<div class="center hero-unit">
	U izradi!
</div>
<div class='blog'>
	So far done:
	
  <ul style= "color: #000000 !important;">
		<li>A few static pages, including the one you are visiting right now</li>
		<li>A whole lot of creation and deletion, the database migrations are a real mess</li>
		<li>User sign in/ sign out</li>
		<li>Cookies are enabled, permanent user sign in is achieved this way</li>
		<li>Implemented the ability for users to upload profile pictures</li>
		<li>Heavy usage of bootstrap to make it remotley attractive</li>
		<li>A bunch of small stuff, like the mail_to link in the footer</li>
		<li>Added a bunch of tests including factorygirls tests. Most of them are copied from the internet *blush*</li>
		<li>Added a first aid favicon, just for the fun of it</li>
	</ul>
</div>


app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<div class="center hero-unit">
  <h2>Zanimaju vas naše usluge</h2>
    
  <p>Pretplatite se na obavijesti a mi ćemo vas redovno obavještavati o novostima.</p>
    
  <form action="" method="post">
    <div class="input-prepend"><span class="add-on"><i class="icon-envelope"></i></span>
        <input type="text" id="" name="" placeholder="your@email.com">
    </div>
    <br />
    <input type="submit" value="Subscribe Now!" class="btn btn-inverse" />
  </form>
</div>

app/views/static_pages/loginerror.html.erb
<% provide(:title, 'Ups') %>
<div class="center hero-unit">
	<h1>Welcome to Gags on Rails</h1>
	<div class="alert alert-error"><h2>
		Seems like You will have to loggin to do that
	</h2>
</div>
<%= link_to "Sign in now!", signin_path, class: "btn btn-large btn-primary" %>
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/search.html.erb
<div class="row">
	<h1>You searched for: <%="#{@search}"%></h1>


	<div id="users" class="span4">
		<h1>Users (<%=@users.length%>)</h1>
		<ul class="users">
			<%= render @users %>
		</ul>
	</div>

	<div id="microposts" class="span4 offset1">
		<h1>Microposts (<%=@microposts.length%>)</h1>
		<ul class="microposts">
			<%= render @microposts %>
		</ul>
	</div>

	<div id="gags" class="span3 offset2">
		<h1>Gags (<%=@gags.length%>)</h1>
		<ul class="users">
			<%= render @gags %>
		</ul>
	</div>


</div>